name: gpt-pr-bot
on:
  issue_comment:
    types: [created]

permissions:
  contents: write          # needed to push branches
  pull-requests: write     # needed to comment / open PRs
  issues: read

jobs:
  run:
    # Only run on PR comments that start with "/gpt "
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/gpt ')
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_STAGING }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput('head_ref', pr.data.head.ref);
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.pr.outputs.head_ref }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i @octokit/rest openai@4
      - name: Run bot
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          ACTOR: ${{ github.actor }}
        run: node .github/scripts/gpt-pr-bot.mjs
